### ISSUE TITLE
Shouldn't it be debug only?

### ISSUE THREAD

**Issue by ManuelDeLeon** [rwatts3/meteor-packages#5]
This is sick! I'll definitely do a screen cast on it.

Q: Shouldn't it be debug only?

**Comment by rwatts3** [comment]
Thank you. 

Actually in this case I believe I would want to leave it as available on the site and here is the reason why. If you throw a conditional around the meteordump to either check for a session variable of your PC , or check for if your ip address matches , You could use meteordump to dump out potential objects, or variables on a production site that may be causing issus, or throwing errors. Without interrupting the current user. 

But I will look more into it to be sure.

**Comment by rwatts3** [comment]
Does this answer your previous question ?

**Comment by ManuelDeLeon** [comment]
Yes but I strongly disagree :)

**Comment by rwatts3** [comment]
I'd like to hear your thoughts.  V 0.1.0 is just the start lots of
improvements to follow
